using Azure;
using Azure.AI.OpenAI;
using Azure.Identity;
using Microsoft.Extensions.Options;
using OpenAI.Chat;
using SelfHostedGovernanceAgent.Api.Models;
using SelfHostedGovernanceAgent.Api.Options;

namespace SelfHostedGovernanceAgent.Api.Services;

public sealed class FoundryChatService : IFoundryChatService
{
    private const string SystemPrompt =
        "Eres un agente de gobierno de despliegue de agentes empresariales. Responde de forma breve, estructurada y enfocada en controles de despliegue, seguridad, pruebas, identidad, APIM, AKS y evaluación.";

    private readonly AzureOpenAIOptions _options;
    private readonly ILogger<FoundryChatService> _logger;

    public FoundryChatService(IOptions<AzureOpenAIOptions> options, ILogger<FoundryChatService> logger)
    {
        _options = options.Value;
        _logger = logger;
    }

    public async Task<GovernanceChatResponse> AskAsync(GovernanceChatRequest request, CancellationToken cancellationToken)
    {
        var endpoint = ResolveSetting("AZURE_OPENAI_ENDPOINT", _options.Endpoint);
        var deploymentName = ResolveSetting("AZURE_OPENAI_DEPLOYMENT_NAME", _options.DeploymentName);

        if (string.IsNullOrWhiteSpace(endpoint))
        {
            throw new InvalidOperationException("Azure OpenAI endpoint is not configured. Set AZURE_OPENAI_ENDPOINT or AzureOpenAI:Endpoint.");
        }

        if (string.IsNullOrWhiteSpace(deploymentName))
        {
            throw new InvalidOperationException("Azure OpenAI deployment name is not configured. Set AZURE_OPENAI_DEPLOYMENT_NAME or AzureOpenAI:DeploymentName.");
        }

        try
        {
            var credential = new DefaultAzureCredential();
            var client = new AzureOpenAIClient(new Uri(endpoint), credential);
            var chatClient = client.GetChatClient(deploymentName);

            var completion = await chatClient.CompleteChatAsync(
                [
                    new SystemChatMessage(SystemPrompt),
                    new UserChatMessage(request.Message)
                ],
                cancellationToken: cancellationToken);

            var content = completion.Value.Content.Count > 0
                ? completion.Value.Content[0].Text
                : string.Empty;

            return new GovernanceChatResponse(
                content,
                deploymentName,
                BuildAuthenticationLabel(),
                "Response generated by GovernanceAgent using Azure OpenAI with DefaultAzureCredential.");
        }
        catch (AuthenticationFailedException ex)
        {
            _logger.LogError(ex, "Azure authentication failed.");
            throw new InvalidOperationException("Azure authentication failed. Run az login locally or verify Workload Identity, AZURE_CLIENT_ID and RBAC in AKS.", ex);
        }
        catch (RequestFailedException ex) when (ex.Status is 401 or 403)
        {
            _logger.LogError(ex, "Azure OpenAI authorization failed.");
            throw new InvalidOperationException("Azure OpenAI authorization failed. Verify RBAC: Cognitive Services OpenAI User on the target resource.", ex);
        }
        catch (RequestFailedException ex)
        {
            _logger.LogError(ex, "Azure OpenAI request failed.");
            throw new InvalidOperationException($"Azure OpenAI request failed with status {ex.Status}. Verify endpoint, deployment name and Azure AI Foundry / Azure OpenAI availability.", ex);
        }
        catch (UriFormatException ex)
        {
            throw new InvalidOperationException("Azure OpenAI endpoint is not a valid URI.", ex);
        }
    }

    private static string ResolveSetting(string environmentVariableName, string configuredValue)
    {
        var environmentValue = Environment.GetEnvironmentVariable(environmentVariableName);
        return string.IsNullOrWhiteSpace(environmentValue) ? configuredValue : environmentValue;
    }

    private static string BuildAuthenticationLabel()
    {
        return string.IsNullOrWhiteSpace(Environment.GetEnvironmentVariable("AZURE_CLIENT_ID"))
            ? "DefaultAzureCredential"
            : "DefaultAzureCredential / Workload Identity";
    }
}
